# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pham Ngoc Quan
name: Pham Ngoc Quan
position: AI Research Resident 
email: ngocquanofficial@gmail.com
description: >-
  I am a third-year student at [Hanoi University of Science and Technology](https://hust.edu.vn/en/), 
  currently working as a research assistant at the BKAI Laboratory under the guidance of [Dr. Nguyen Thi Thu Trang](https://soict.hust.edu.vn/en/ph-d-nguyen-thi-thu-trang.html),
   and as an AI Resident at [VinAI Research](https://www.vinai.io/), mentored by [Prof. Le Minh Trung](https://research.monash.edu/en/persons/trung-le). My primary research interests lie in Bayesian inference, the theoretical foundations of machine learning, and natural language processing for low-resource languages such as Vietnamese.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ngocquan.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ngocquanai
github_username: ngocquanai
# google_scholar: HVZb-5oAAAAJ
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
